// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FullConnection: typeof import('./src/components/FullConnection.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NeighboorConnection: typeof import('./src/components/NeighboorConnection.vue')['default']
    RandomConnection: typeof import('./src/components/RandomConnection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
  }
}

export {}
